calculator
achal-webonise/-1-JS-Assignment pull request #3
Opened 2024-06-11 20:13 UTC by achal-webonise

2024-07-04 07:20 UTC, aashiq-webonise commented on Calculator/calculator.html
> +</html>
Add End of line

2024-07-04 07:21 UTC, aashiq-webonise commented on Calculator/calculator.js
> +        { label: "1", onClick: () => handleNumberClick("1") },
Please Create a generic Function , maybe use an array for your numbers , this approach seems redundant

2024-07-04 07:25 UTC, aashiq-webonise commented on Calculator/calculator.js
> +import React, { useState } from "eact";
This is one way of doing it , but please use Create React app for the same

2024-07-26 06:07 UTC, swapnil-webonise requested changes

2024-07-26 06:07 UTC, swapnil-webonise commented on node_modules/.bin/acorn
We should not commit node_modules folder, it should be in git ignore

2024-07-26 09:17 UTC, closed without merging